<a href="https://colab.research.google.com/github/vzyhug/200123035_14DHTH07_DL/blob/main/Pandas/THDLN_Buoi1_BTTL_NumpyPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [71]:
import numpy as np
import pandas as pd

In [ ]:
# bai 1
# Tạo mảng ngẫu nhiên kích thước 3x3 trong khoảng [0, 20]
# Lưu ý: np.random.randint(low, high, size) thì 'high' sẽ không bao gồm trong kết quả
# nên ta dùng 21 để có thể xuất hiện số 20.
mang = np.random.randint(0, 21, size=(3, 3))

print("Mảng vừa tạo:")
print(mang)

# 2. Kiểm tra tất cả các phần tử có khác 0 hay không
# Biểu thức (mang != 0) sẽ trả về một mảng Boolean (True/False)
# Hàm np.all() trả về True nếu tất cả phần tử trong mảng Boolean đó là True
ket_qua = np.all(mang != 0)

print("\n--- Kết quả kiểm tra ---")
if ket_qua:
    print("Tất cả các phần tử trong mảng đều khác 0.")
else:
    print("Có ít nhất một phần tử bằng 0 trong mảng.")

Mảng vừa tạo:
[[ 6  4 10]
 [20  0  4]
 [ 3  6  6]]

--- Kết quả kiểm tra ---
Có ít nhất một phần tử bằng 0 trong mảng.


In [ ]:
# bai2
# Tạo mảng ngẫu nhiên kích thước 3x3 trong khoảng [0, 20]
mang = np.random.randint(0, 21, size=(3, 3))

print("Mảng vừa tạo:")
print(mang)
# 2. Kiểm tra xem có TỒN TẠI phần tử nào khác 0 hay không
# Biểu thức (mang != 0) tạo mảng Boolean
# np.any() trả về True nếu có ít nhất một giá trị True
ton_tai_khac_0 = np.any(mang != 0)

print("\n--- Kết quả kiểm tra (any) ---")
if ton_tai_khac_0:
    print("Có tồn tại ít nhất một phần tử khác 0 trong mảng.")
else:
    print("Tất cả các phần tử đều bằng 0.")

Mảng vừa tạo:
[[11 19 10]
 [ 0  9  7]
 [ 9  1  1]]

--- Kết quả kiểm tra (any) ---
Có tồn tại ít nhất một phần tử khác 0 trong mảng.


In [ ]:
#bai 3
# Tạo dữ liệu mẫu
# Mảng 1 chiều
a1 = np.array([10, 20, 30])
b1 = np.array([15, 20, 25])

# Mảng 2 chiều (2x2)
a2 = np.array([[1, 5], [8, 12]])
b2 = np.array([[2, 4], [8, 10]])

def so_sanh_mang(arr1, arr2, label):
    print(f"--- So sánh mảng {label} ---")
    print(f"Mảng A:\n{arr1}")
    print(f"Mảng B:\n{arr2}")

    print("1. Greater (A > B):      ", np.greater(arr1, arr2))
    print("2. Greater Equal (A >= B):", np.greater_equal(arr1, arr2))
    print("3. Less (A < B):         ", np.less(arr1, arr2))
    print("4. Less Equal (A <= B):   ", np.less_equal(arr1, arr2))
    print("\n")

# Thực thi
so_sanh_mang(a1, b1, "1 chiều")
so_sanh_mang(a2, b2, "2 chiều")

--- So sánh mảng 1 chiều ---
Mảng A:
[10 20 30]
Mảng B:
[15 20 25]
1. Greater (A > B):       [False False  True]
2. Greater Equal (A >= B): [False  True  True]
3. Less (A < B):          [ True False False]
4. Less Equal (A <= B):    [ True  True False]


--- So sánh mảng 2 chiều ---
Mảng A:
[[ 1  5]
 [ 8 12]]
Mảng B:
[[ 2  4]
 [ 8 10]]
1. Greater (A > B):       [[False  True]
 [False  True]]
2. Greater Equal (A >= B): [[False  True]
 [ True  True]]
3. Less (A < B):          [[ True False]
 [False False]]
4. Less Equal (A <= B):    [[ True False]
 [ True False]]




In [ ]:
# bai 4
# mang 10 so 1
mang1 = np.ones(10,dtype=np.int32)
print("mang 10 so 1: ",mang1)
# mang 10 so 0
mang2 = np.zeros(10,dtype=np.int32)
print("mang 10 so 0: ",mang2)
# mang 10 so 5
mang3 = np.full(10, 5)
print("mang 10 so 5: ",mang3)
#

mang 10 so 1:  [1 1 1 1 1 1 1 1 1 1]
mang 10 so 0:  [0 0 0 0 0 0 0 0 0 0]
mang 10 so 5:  [5 5 5 5 5 5 5 5 5 5]


In [ ]:
# bai 5
mang = np.arange(30, 71,2, dtype=np.int32)
print(mang)
#

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
# bai 6
matrix = np.identity(3, dtype=np.int32)
print(matrix)
#

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# bai 7
mang = np.linspace(15, 55, 10,dtype=np.int32)
print("day du: ",mang)
print("loai bo dau-cuoi: ",mang[1:-1])
#

day du:  [15 19 23 28 32 37 41 46 50 55]
loai bo dau-cuoi:  [19 23 28 32 37 41 46 50]


In [ ]:
# bai 8
mang = np.linspace(0, 20, 20,dtype=np.int32)
print("day du: ",mang)
# doi dau
mang[(mang >= 9) & (mang <= 15)] *= -1
print("doi dau [9;15]:\n ",mang)

day du:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 20]
doi dau [9;15]:
  [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  20]


In [ ]:
# bai 9
matrix = np.random.randint(low=10,high=21,size=(3, 3))
print(matrix)

[[12 13 16]
 [10 15 14]
 [10 12 14]]


In [ ]:
# bai 10
# matran full 0 --> chuyen hang/cot dau-cuoi ve 1
matrix = np.zeros((10,10),dtype=np.int32)
# hang dau --> 1
matrix[0,:]=1
# hang cuoi -->1
matrix[-1,:]=1
# cot dau --> 1
matrix[:,0]=1
# cot cuoi
matrix[:,-1]=1
print(matrix)
#

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [2]:
# bai 11
matrix = np.diag([1, 2, 3, 4, 5])
print(matrix)
#


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [10]:
# bai 12
matrix = np.random.randint(low=0,high=10,size=(3,3,3))
print(matrix)
#
print("\ntong theo hang")
sum_row = np.sum(matrix, axis=1)
print(sum_row)
print("\ntong theo cot")
sum_col = np.sum(matrix, axis=2)
print(sum_col)
#

[[[3 7 8]
  [5 5 0]
  [9 2 6]]

 [[9 2 0]
  [6 3 5]
  [5 0 8]]

 [[5 8 3]
  [8 4 3]
  [5 3 7]]]

tong theo hang
[[17 14 14]
 [20  5 13]
 [18 15 13]]

tong theo cot
[[18 10 17]
 [11 14 13]
 [16 15 15]]


In [15]:
# bai 13
vt1 = np.random.randint(low=0,high=10,size=10)
vt2 = np.random.randint(low=0,high=10,size=10)
print("vt1: ",vt1)
print("vt2: ",vt2)
print("\ndot product = ",np.dot(vt1, vt2))

#

vt1:  [8 8 0 8 6 3 4 3 2 6]
vt2:  [1 8 0 0 3 9 9 7 8 7]

dot product =  232


In [70]:
# bai 14
matrixA = np.random.randint(low=0,high=10,size=(4,3))
print("matrix A : \n",matrixA)
vtY = np.random.randint(low=0,high=10,size=3)
print("\nvector Y :",vtY)
result =[]
print("them vector Y vao tung dong cua ma tran A:")
# cach 1
print("cach 1:")
for i in range(0,matrixA.shape[0]):
    row = np.hstack((matrixA[i,:],vtY))
    result.append(row)
print(np.array(result))
# cach 2
print("cach 2:")
vtY_tiled = np.tile(vtY, (matrixA.shape[0], 1))
result = np.hstack((matrixA, vtY_tiled))
print(result)
#

#

matrix A : 
 [[6 7 9]
 [6 9 9]
 [8 6 2]
 [5 4 4]]

vector Y : [0 5 5]
them vector Y vao tung dong cua ma tran A:
cach 1:
[[6 7 9 0 5 5]
 [6 9 9 0 5 5]
 [8 6 2 0 5 5]
 [5 4 4 0 5 5]]
cach 2:
[[6 7 9 0 5 5]
 [6 9 9 0 5 5]
 [8 6 2 0 5 5]
 [5 4 4 0 5 5]]


In [87]:
# bai 15
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Series 1:\n", s1)
print("\nSeries 2:\n", s2)

# 1. Cong
res_add = s1 + s2
print("\nCong\n", res_add)

# 2. Tru
res_sub = s1 - s2
print("\nTru\n", res_sub)

# 3. Nhan
res_mul = s1 * s2
print("\nNhan\n", res_mul)

# 4. Chia
res_div = s1 / s2
print("\nChia\n", res_div)

Series 1:
 0     2
1     4
2     6
3     8
4    10
dtype: int64

Series 2:
 0     1
1     3
2     5
3     7
4    10
dtype: int64

Cong
 0     3
1     7
2    11
3    15
4    20
dtype: int64

Tru
 0    1
1    1
2    1
3    1
4    0
dtype: int64

Nhan
 0      2
1     12
2     30
3     56
4    100
dtype: int64

Chia
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64


In [98]:
# bai 16 :
r = np.random.randint(low=0,high=10,size=(6,4))
df = pd.DataFrame(r,columns=['col1','col2','col3','col4'])
print(df)
print("\nchuyen cot dau thanh series:")
df.iloc[:,0]

   col1  col2  col3  col4
0     5     0     0     9
1     6     8     3     3
2     2     7     3     4
3     0     1     6     4
4     8     5     1     9
5     1     4     5     7

chuyen cot dau thanh series:


,col1
0,5
1,6
2,2
3,0
4,8
5,1


In [122]:
3 # bai 17
r = np.random.randint(low=0,high=10,size=(4,3))
df = pd.DataFrame(r,columns=['col1','col2','col3'])
print(df)
# sap xep theo cot
print("giam theo cot 1 :")
sort_df1=df.sort_values(by='col1', ascending=False)
print(sort_df1)
#
print("giam theo cot 2 :")
sort_df2=df.sort_values(by='col2', ascending=False)
print(sort_df2)
print("giam theo cot 3 :")
sort_df3=df.sort_values(by='col3', ascending=False)
print(sort_df3)

# theo thu tu 1,2,3
print("giam theo thu tu 1,2,3 :")
sort_df4=df.sort_values(by=['col1','col2','col3'], ascending=False)
print(sort_df4)

   col1  col2  col3
0     3     1     1
1     7     8     9
2     7     3     6
3     2     6     5
giam theo cot 1 :
   col1  col2  col3
1     7     8     9
2     7     3     6
0     3     1     1
3     2     6     5
giam theo cot 2 :
   col1  col2  col3
1     7     8     9
3     2     6     5
2     7     3     6
0     3     1     1
giam theo cot 3 :
   col1  col2  col3
1     7     8     9
2     7     3     6
3     2     6     5
0     3     1     1
giam theo thu tu 1,2,3 :
   col1  col2  col3
1     7     8     9
2     7     3     6
0     3     1     1
3     2     6     5
