<a href="https://colab.research.google.com/github/vzyhug/200123035_14DHTH07_DL/blob/main/Pandas/THDLN_Buoi1_BTTL_NumpyPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
# bai 1
# Tạo mảng ngẫu nhiên kích thước 3x3 trong khoảng [0, 20]
# Lưu ý: np.random.randint(low, high, size) thì 'high' sẽ không bao gồm trong kết quả
# nên ta dùng 21 để có thể xuất hiện số 20.
mang = np.random.randint(0, 21, size=(3, 3))

print("Mảng vừa tạo:")
print(mang)

# 2. Kiểm tra tất cả các phần tử có khác 0 hay không
# Biểu thức (mang != 0) sẽ trả về một mảng Boolean (True/False)
# Hàm np.all() trả về True nếu tất cả phần tử trong mảng Boolean đó là True
ket_qua = np.all(mang != 0)

print("\n--- Kết quả kiểm tra ---")
if ket_qua:
    print("Tất cả các phần tử trong mảng đều khác 0.")
else:
    print("Có ít nhất một phần tử bằng 0 trong mảng.")

Mảng vừa tạo:
[[ 6  4 10]
 [20  0  4]
 [ 3  6  6]]

--- Kết quả kiểm tra ---
Có ít nhất một phần tử bằng 0 trong mảng.


In [6]:
# bai2
# Tạo mảng ngẫu nhiên kích thước 3x3 trong khoảng [0, 20]
mang = np.random.randint(0, 21, size=(3, 3))

print("Mảng vừa tạo:")
print(mang)
# 2. Kiểm tra xem có TỒN TẠI phần tử nào khác 0 hay không
# Biểu thức (mang != 0) tạo mảng Boolean
# np.any() trả về True nếu có ít nhất một giá trị True
ton_tai_khac_0 = np.any(mang != 0)

print("\n--- Kết quả kiểm tra (any) ---")
if ton_tai_khac_0:
    print("Có tồn tại ít nhất một phần tử khác 0 trong mảng.")
else:
    print("Tất cả các phần tử đều bằng 0.")

Mảng vừa tạo:
[[11 19 10]
 [ 0  9  7]
 [ 9  1  1]]

--- Kết quả kiểm tra (any) ---
Có tồn tại ít nhất một phần tử khác 0 trong mảng.


In [7]:
#bai 3
# Tạo dữ liệu mẫu
# Mảng 1 chiều
a1 = np.array([10, 20, 30])
b1 = np.array([15, 20, 25])

# Mảng 2 chiều (2x2)
a2 = np.array([[1, 5], [8, 12]])
b2 = np.array([[2, 4], [8, 10]])

def so_sanh_mang(arr1, arr2, label):
    print(f"--- So sánh mảng {label} ---")
    print(f"Mảng A:\n{arr1}")
    print(f"Mảng B:\n{arr2}")

    print("1. Greater (A > B):      ", np.greater(arr1, arr2))
    print("2. Greater Equal (A >= B):", np.greater_equal(arr1, arr2))
    print("3. Less (A < B):         ", np.less(arr1, arr2))
    print("4. Less Equal (A <= B):   ", np.less_equal(arr1, arr2))
    print("\n")

# Thực thi
so_sanh_mang(a1, b1, "1 chiều")
so_sanh_mang(a2, b2, "2 chiều")

--- So sánh mảng 1 chiều ---
Mảng A:
[10 20 30]
Mảng B:
[15 20 25]
1. Greater (A > B):       [False False  True]
2. Greater Equal (A >= B): [False  True  True]
3. Less (A < B):          [ True False False]
4. Less Equal (A <= B):    [ True  True False]


--- So sánh mảng 2 chiều ---
Mảng A:
[[ 1  5]
 [ 8 12]]
Mảng B:
[[ 2  4]
 [ 8 10]]
1. Greater (A > B):       [[False  True]
 [False  True]]
2. Greater Equal (A >= B): [[False  True]
 [ True  True]]
3. Less (A < B):          [[ True False]
 [False False]]
4. Less Equal (A <= B):    [[ True False]
 [ True False]]




In [11]:
# bai 4
# mang 10 so 1
mang1 = np.ones(10,dtype=np.int32)
print("mang 10 so 1: ",mang1)
# mang 10 so 0
mang2 = np.zeros(10,dtype=np.int32)
print("mang 10 so 0: ",mang2)
# mang 10 so 5
mang3 = np.full(10, 5)
print("mang 10 so 5: ",mang3)
#

mang 10 so 1:  [1 1 1 1 1 1 1 1 1 1]
mang 10 so 0:  [0 0 0 0 0 0 0 0 0 0]
mang 10 so 5:  [5 5 5 5 5 5 5 5 5 5]


In [12]:
# bai 5
mang = np.arange(30, 71,2, dtype=np.int32)
print(mang)
#

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [13]:
# bai 6
matrix = np.identity(3, dtype=np.int32)
print(matrix)
#

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [25]:
# bai 7
mang = np.linspace(15, 55, 10,dtype=np.int32)
print("day du: ",mang)
print("loai bo dau-cuoi: ",mang[1:-1])
#

day du:  [15 19 23 28 32 37 41 46 50 55]
loai bo dau-cuoi:  [19 23 28 32 37 41 46 50]


In [35]:
# bai 8
mang = np.linspace(0, 20, 20,dtype=np.int32)
print("day du: ",mang)
# doi dau
mang[(mang >= 9) & (mang <= 15)] *= -1
print("doi dau [9;15]:\n ",mang)

day du:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 20]
doi dau [9;15]:
  [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  20]


In [41]:
# bai 9
matrix = np.random.randint(low=10,high=21,size=(3, 3))
print(matrix)

[[12 13 16]
 [10 15 14]
 [10 12 14]]


In [47]:
# bai 10
# matran full 0 --> chuyen hang/cot dau-cuoi ve 1
matrix = np.zeros((10,10),dtype=np.int32)
# hang dau --> 1
matrix[0,:]=1
# hang cuoi -->1
matrix[-1,:]=1
# cot dau --> 1
matrix[:,0]=1
# cot cuoi
matrix[:,-1]=1
print(matrix)
#

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]
