<a href="https://colab.research.google.com/github/vzyhug/200123035_14DHTH07_DL/blob/main/Pandas/THDLN_Buoi1_BTTL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Input , Add , Subtract , Multiply , Dense ,Layer , Lambda
from tensorflow.keras.models import Model

In [ ]:
#bai 1:
ts1 = tf.zeros([2,3])
print(ts1)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [ ]:
# bai 2:
tensorX = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
tensor2 = tf.zeros(dtype=tensorX.dtype,shape=tensorX.get_shape())
print(tensor2)

tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]], shape=(3, 3), dtype=int32)


In [ ]:
# bai 3 :
ts3 = tf.fill([2,3],5)
print(ts3)

tf.Tensor(
[[5 5 5]
 [5 5 5]], shape=(2, 3), dtype=int32)


In [ ]:

#bai 4
ts4_random = tf.random.uniform(shape=[50], minval=5, maxval=10)

print(ts4_random)

tf.Tensor(
[9.573004  8.791376  9.923367  5.6374016 8.618528  8.562423  9.593727
 8.020974  5.365312  9.622734  9.082889  6.0961156 6.0904207 5.880726
 6.843548  9.000378  6.5119214 9.965195  8.864032  6.6484985 8.14128
 8.745199  7.8554907 5.4291463 9.544598  9.682928  5.399335  9.33033
 9.665761  5.0432625 9.73801   7.3623633 5.3983645 9.188219  9.398725
 6.7395897 5.71809   6.159507  8.659869  7.9728603 9.079193  5.8237977
 7.9008245 8.223892  5.644247  7.402547  7.0286746 5.2861543 6.509059
 8.914375 ], shape=(50,), dtype=float32)


In [ ]:
#bai5
ts5_range = tf.range(10,102,delta=2)
print(ts5_range)

tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


In [ ]:
#bai 6
ts_normal = tf.random.normal(shape=[3, 2], mean=0.0, stddev=2.0)
print(ts_normal)

tf.Tensor(
[[ 3.9801092   0.17654662]
 [-0.7135354   0.41010642]
 [ 4.0428653  -0.13001068]], shape=(3, 2), dtype=float32)


In [ ]:
#bai 7
ts_uniform = tf.random.uniform(shape=[3, 2], minval=0, maxval=2)
print(ts_uniform)

tf.Tensor(
[[0.7007706  0.6793952 ]
 [0.62441945 0.02823043]
 [1.4242504  1.1472833 ]], shape=(3, 2), dtype=float32)


In [ ]:
# bai 8
tensorX= tf.constant([[1,2],[2,3],[5,6]])
print(tensorX)
print(tf.random.shuffle(tensorX))

tf.Tensor(
[[1 2]
 [2 3]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [1 2]
 [5 6]], shape=(3, 2), dtype=int32)


In [ ]:
# bai 9

X = tf.random.uniform(shape=(10, 10, 3), minval=0, maxval=256, dtype=tf.int32)

shuffled_crop = tf.image.random_crop(X, size=[5, 5, 3])

print("Kích thước tensor gốc:", X.shape)
print("Kích thước sau khi random crop:", shuffled_crop.shape)
print("\nNội dung tensor sau khi cắt:\n", shuffled_crop.numpy())

Kích thước tensor gốc: (10, 10, 3)
Kích thước sau khi random crop: (5, 5, 3)

Nội dung tensor sau khi cắt:
 [[[200   3  78]
  [218  84 124]
  [ 80 153 249]
  [218  62  60]
  [204  38 155]]

 [[ 25 255 211]
  [207 164 254]
  [180 156 125]
  [ 47 147 120]
  [249   3  81]]

 [[ 95  93  44]
  [140 238 154]
  [ 92 172 118]
  [157  20 131]
  [241 232  70]]

 [[127 212 143]
  [172   1  49]
  [223 210 183]
  [157 166 236]
  [  5 226  74]]

 [[ 34  49  45]
  [ 23 231 215]
  [205 242 233]
  [195  69 214]
  [145  55 144]]]


In [ ]:
# bai 10
ts_x = tf.random.uniform((5,),minval=0,maxval=999,dtype=tf.int32)
ts_y = tf.random.uniform((5,),minval=0,maxval=999,dtype=tf.int32)
print("tensor x: ",ts_x.numpy())
print("tensor y: ",ts_y.numpy())
#
result = tf.where(ts_x<ts_y,ts_x+ts_y,ts_x-ts_y) # so sanh tung phan tu tsX vs tsY
print("ket qua: ",result.numpy())

tensor x:  [686 693 930 267 873]
tensor y:  [140 219 651 424 872]
ket qua:  [546 474 279 691   1]


In [ ]:
# bai 11 : (3,2) va (2,3) khong cong duoc --> transpose 1 trong 2
ts1 = tf.random.uniform((3,2),minval=5,maxval=11,dtype=tf.int32)
ts2 = tf.random.uniform((2,3),minval=15,maxval=21,dtype=tf.int32)
print("ts1:\n",ts1.numpy())
print("ts2:\n",ts2.numpy())
# dao chieu tensor : tf.transpose
ts2_transpose = tf.transpose(ts2)
print("ts2 transpose:\n",ts2_transpose.numpy())
# chuyen phan tu o duong cheo thanh 0 de x+y van giu dg cheo x
# 1. xem phan tu duong cheo : tf.eye(n_dong ,n_cot,dtypee : bool )
diag_mask = tf.eye(num_rows=3,num_columns=2,dtype=tf.bool)
print("mask duong cheo:\n",diag_mask.numpy())
# 2. gan phan tu 0
final_ts2 = tf.where(diag_mask,0,ts2_transpose)
print("ts2 chuan hoa :\n",final_ts2.numpy())
# cong 2 tensor
result = tf.add(ts1,final_ts2)
print("ket qua:\n",result.numpy())

ts1:
 [[ 9  5]
 [ 6 10]
 [ 7  7]]
ts2:
 [[18 19 16]
 [20 19 20]]
ts2 transpose:
 [[18 20]
 [19 19]
 [16 20]]
mask duong cheo:
 [[ True False]
 [False  True]
 [False False]]
ts2 chuan hoa :
 [[ 0 20]
 [19  0]
 [16 20]]
ket qua:
 [[ 9 25]
 [25 10]
 [23 27]]


In [34]:
# bai 12:
# Hàm tạo tensor
def create_tensors():
    x = tf.random.uniform((3, 2, 2), minval=1, maxval=10, dtype=tf.float32)
    y = tf.random.uniform((3, 2, 2), minval=1, maxval=10, dtype=tf.float32)
    return x, y
#  2. Các hàm toán học
@tf.function
def add(x, y):
    return x + y

@tf.function
def subtract(x, y):
    return x - y

@tf.function
def multiply(x, y):
    return x * y

@tf.function
def divide(x, y):
    return x / y

#  3. Test
x, y = create_tensors()

print("x =\n", x.numpy())
print("y =\n", y.numpy())

print("\nCong:\n", add(x, y).numpy())
print("\nTru:\n", subtract(x, y).numpy())
print("\nNhan:\n", multiply(x, y).numpy())
print("\nChia:\n", divide(x, y).numpy())

x =
 [[[8.837748  1.3415804]
  [7.892598  7.2020783]]

 [[7.2622037 4.54169  ]
  [1.0440805 1.4429743]]

 [[7.68005   5.636195 ]
  [8.460439  4.1462054]]]
y =
 [[[7.2307596 1.7233102]
  [9.406052  5.865939 ]]

 [[6.415085  4.3747253]
  [2.6724346 1.9843868]]

 [[2.2899313 5.696579 ]
  [2.2588391 8.013129 ]]]

Cong:
 [[[16.068508   3.0648906]
  [17.298649  13.068018 ]]

 [[13.677288   8.916415 ]
  [ 3.716515   3.427361 ]]

 [[ 9.969981  11.332774 ]
  [10.719278  12.159334 ]]]

Tru:
 [[[ 1.606988   -0.38172984]
  [-1.5134535   1.3361392 ]]

 [[ 0.84711885  0.16696453]
  [-1.6283541  -0.5414125 ]]

 [[ 5.3901186  -0.0603838 ]
  [ 6.2015996  -3.8669238 ]]]

Nhan:
 [[[63.90363    2.3119593]
  [74.23818   42.246952 ]]

 [[46.587654  19.868647 ]
  [ 2.7902367  2.8634193]]

 [[17.586786  32.107033 ]
  [19.11077   33.22408  ]]]

Chia:
 [[[1.2222433  0.77849036]
  [0.8390979  1.2277793 ]]

 [[1.1320511  1.0381657 ]
  [0.39068514 0.72716385]]

 [[3.3538342  0.98939997]
  [3.7454808  0.5174265 ]]]

In [5]:
# bai 13 : model tinh tong 2 ma tran
#input
x_input = Input(shape=(3,3),dtype=tf.int32)
y_input = Input(shape=(3,3),dtype=tf.int32)
# output
x_output = Add()([x_input,y_input])
# model
model = Model(inputs=[x_input,y_input],outputs=x_output)
# data
n = int(input("nhap n: "))
x_data = tf.random.uniform((n,3,3),minval=1,maxval=10,dtype=tf.int32)
y_data = tf.random.uniform((n,3,3),minval=1,maxval=10,dtype=tf.int32)
print("x_data:\n",x_data.numpy())
print("y_data:\n",y_data.numpy())

# result
result = model([x_data,y_data])
print("result:\n",result.numpy())


nhap n: 2
x_data:
 [[[5 6 6]
  [3 9 3]
  [9 2 8]]

 [[4 1 8]
  [7 9 4]
  [7 7 5]]]
y_data:
 [[[8 9 4]
  [9 2 7]
  [8 7 8]]

 [[8 6 4]
  [8 9 1]
  [4 3 7]]]
result:
 [[[13 15 10]
  [12 11 10]
  [17  9 16]]

 [[12  7 12]
  [15 18  5]
  [11 10 12]]]


In [12]:
# bai 14 : model tinh hieu va tich cua ma tran
# input
x_input = Input(shape=(3,3),dtype=tf.int32)
y_input = Input(shape=(3,3),dtype=tf.int32)
# output
output_subtrack = Subtract()([x_input,y_input])
output_multiply = Multiply()([x_input,y_input])
# model
model = Model(inputs=[x_input,y_input],outputs=[output_subtrack,output_multiply])
# data
n = int(input("nhap n: "))
x_data = tf.random.uniform(shape=(1,3,3),minval=1,maxval=10,dtype=tf.int32)
y_data = tf.random.uniform(shape=(1,3,3),minval=1,maxval=10,dtype=tf.int32)
print("x_data:\n",x_data.numpy())
print("y_data:\n",y_data.numpy())
# result
result = model([x_data,y_data])
print("result subtrack:\n",result[0].numpy())
print("result multiply:\n",result[1].numpy())


nhap n: 2
x_data:
 [[[5 7 3]
  [5 7 8]
  [3 6 8]]]
y_data:
 [[[6 5 2]
  [8 7 7]
  [9 3 4]]]
result subtrack:
 [[[-1  2  1]
  [-3  0  1]
  [-6  3  4]]]
result multiply:
 [[[30 35  6]
  [40 49 56]
  [27 18 32]]]


In [18]:
# bai 15 : model tinh chu vi HCN
# input
rect_lenght = Input(shape=(1,),dtype=tf.int32)
rect_width = Input(shape=(1,),dtype=tf.int32)
# output
output = (Add()([rect_lenght,rect_width]))*2
# model
model = Model(inputs=[rect_lenght,rect_width],outputs=output)
# data
input_lenght = int(input("nhap chieu dai: "))
input_width = int(input("nhap chieu rong: "))
rect_lenght_data = tf.constant([input_lenght],dtype=tf.int32)
rect_width_data = tf.constant([input_width],dtype=tf.int32)
# result
result = model.predict([rect_lenght_data,rect_width_data])
print("chu vi hinh chu nhat: ",result)
#

nhap chieu dai: 6
nhap chieu rong: 7


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
chu vi hinh chu nhat:  [[26]]


In [33]:
# bai 16 : model tinh dien tich Hinh hoc Khong gian
# Input
a_input = Input(shape=(1,), dtype=tf.float32)
b_input = Input(shape=(1,), dtype=tf.float32)
c_input = Input(shape=(1,), dtype=tf.float32)

#  (a + b)
a_plus_b = Add()([a_input, b_input])

# Sxung quanh = (a + b) * c * 2
mul1 = Multiply()([a_plus_b, c_input])
Sxq = Multiply()([mul1, tf.constant([2.0])])

#  2ab
ab = Multiply()([a_input, b_input])
two_ab = Multiply()([ab, tf.constant([2.0])])

#  Stoan phan
Stp = Add()([two_ab, Sxq])

#Model
model = Model(inputs=[a_input, b_input, c_input], outputs=Stp)

#  Test
a = float(input("Nhap a: "))
b = float(input("Nhap b: "))
c = float(input("Nhap c: "))

a_data = tf.constant([[a]])
b_data = tf.constant([[b]])
c_data = tf.constant([[c]])

result = model.predict([a_data, b_data, c_data])

print("Dien tich toan phan:", result[0][0])

Nhap a: 3
Nhap b: 4
Nhap c: 5


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
Dien tich toan phan: 94.0


In [68]:
from os import name
# Bai 17 :
# Co so ly thuyet : Hinh thang co 2 canh ben song song la Hinh binh hanh

# input
AD_input = Input(shape=(1,),dtype=tf.int32)
BC_input = Input(shape=(1,),dtype=tf.int32)
AB_input = Input(shape=(1,),dtype=tf.int32)
CD_input = Input(shape=(1,),dtype=tf.int32)

# AD=BC --> Subtract (AD,BC) = 0 , AB=CD --> Sutract(AB,CD)=0
diff_AD_BC = Subtract(name="Subtract_AD_BC")([AD_input,BC_input])
diff_AB_CD = Subtract(name="Subtract_AB_CD")([AB_input,CD_input])

# 0 --> Sai , 1-->Dung
check_zero = Lambda(lambda x: tf.cast(tf.math.equal(x,0),tf.int32),name="Is_zero")
cond_AD_BC = check_zero(diff_AD_BC)
cond_AB_CD = check_zero(diff_AB_CD)
# output : 0*n=0 , 1*1=1
output = Multiply(name="Output")([cond_AD_BC,cond_AB_CD])
# model
model = Model(inputs=[AD_input,BC_input,AB_input,CD_input],outputs=output)
#model.summary()
# data
AD = int(input("nhap AD: "))
BC = int(input("nhap BC: "))
AB = int(input("nhap AB: "))
CD = int(input("nhap CD: "))
AD_data = tf.constant([[AD]],dtype=tf.int32)
BC_data = tf.constant([[BC]],dtype=tf.int32)
AB_data = tf.constant([[AB]],dtype=tf.int32)
CD_data = tf.constant([[CD]],dtype=tf.int32)
# result
result = model.predict([AD_data,BC_data,AB_data,CD_data])
if result[0][0]==1:
    print("song song")
else:
    print("khong song song")
#

nhap AD: 5
nhap BC: 6
nhap AB: 7
nhap CD: 8
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
khong song song


In [81]:
from os import name
# Bai 18 :
# Co so ly thuyet : Hinh thang co 2 canh ben song song la Hinh binh hanh

# input
AD_input = Input(shape=(1,),dtype=tf.int32)
BC_input = Input(shape=(1,),dtype=tf.int32)
AB_input = Input(shape=(1,),dtype=tf.int32)
CD_input = Input(shape=(1,),dtype=tf.int32)

# AD=BC --> Subtract (AD,BC) = 0 , AB=CD --> Sutract(AB,CD)=0
diff_AD_BC = Subtract(name="Subtract_AD_BC")([AD_input,BC_input])
diff_AB_CD = Subtract(name="Subtract_AB_CD")([AB_input,CD_input])

# 0 --> Sai , 1-->Dung
check_zero = Lambda(lambda x: tf.cast(tf.math.equal(x,0),tf.int32),name="Is_zero")
cond_AD_BC = check_zero(diff_AD_BC)
cond_AB_CD = check_zero(diff_AB_CD)
# output : 0*n=0 , 1*1=1
output = Multiply(name="Output")([cond_AD_BC,cond_AB_CD])
# model
model = Model(inputs=[AD_input,BC_input,AB_input,CD_input],outputs=output)
#model.summary()
# data
AD = int(input("nhap AD: "))
BC = int(input("nhap BC: "))
AB = int(input("nhap AB: "))
CD = int(input("nhap CD: "))
AD_data = tf.constant([[AD]],dtype=tf.int32)
BC_data = tf.constant([[BC]],dtype=tf.int32)
AB_data = tf.constant([[AB]],dtype=tf.int32)
CD_data = tf.constant([[CD]],dtype=tf.int32)
# result
result = model.predict([AD_data,BC_data,AB_data,CD_data])
gia_tri_model = result[0][0]

print(f"--- THÔNG SỐ: AD={AD_data}, BC={BC_data}, AB={AB_data}, CD={CD_data} ---")

if gia_tri_model == 1:
    # Model trả về 1 đồng nghĩa với việc cả 2 điều kiện đều thỏa mãn
    print("Trường hợp 1: AD = BC và AB = CD.")
    print("=> Kết luận: AD // BC (Đây là Hình bình hành).")

else:
    # Model trả về 0, nghĩa là ít nhất một trong hai cặp cạnh KHÔNG bằng nhau.
    # Ta dùng if/elif/else để rẽ nhánh tìm nguyên nhân cụ thể:

    if AD_data == BC_data and AB_data != CD_data:
        print("Trường hợp 2: Cạnh bên AD = BC, nhưng đáy AB khác CD.")
        print("=> Kết luận: AD KHÔNG song song với BC (Đây là Hình thang cân).")

    elif AD_data != BC_data and AB_data == CD_data:
        print("Trường hợp 3: Đáy AB = CD, nhưng cạnh bên AD khác BC.")
        print("=> Kết luận: Dữ liệu bị lỗi logic!")
        print("   (Lý thuyết: Hình thang có 2 đáy bằng nhau thì buộc phải là hình bình hành, nên AD phải bằng BC).")

    else:
        # Trường hợp còn lại: ad != bc và ab != cd
        print("Trường hợp 4: Cạnh bên AD khác BC và đáy AB khác CD.")
        print("=> Kết luận: AD KHÔNG song song với BC (Đây là Hình thang thường).")
#

nhap AD: 3
nhap BC: 3
nhap AB: 3
nhap CD: 3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
--- THÔNG SỐ: AD=[[3]], BC=[[3]], AB=[[3]], CD=[[3]] ---
Trường hợp 1: AD = BC và AB = CD.
=> Kết luận: AD // BC (Đây là Hình bình hành).


In [82]:
# bai 19
# Co so ly thuyet : He qua duong trung binh cua tam giac : ( MA=MB && MN // BC && MN = 0.5*BC)--> NA=NC

#input
AM_input = Input(shape=(1,),dtype=tf.int32)
BM_input = Input(shape=(1,),dtype=tf.int32)
BC_input = Input(shape=(1,),dtype=tf.int32)