<a href="https://colab.research.google.com/github/vzyhug/200123035_14DHTH07_DL/blob/main/THDLN_Buoi1_BTTL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
#bai 1:
ts1 = tf.zeros([2,3])
print(ts1)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [ ]:
# bai 2:
tensorX = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
tensor2 = tf.zeros(dtype=tensorX.dtype,shape=tensorX.get_shape())
print(tensor2)

tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]], shape=(3, 3), dtype=int32)


In [ ]:
# bai 3 :
ts3 = tf.fill([2,3],5)
print(ts3)

tf.Tensor(
[[5 5 5]
 [5 5 5]], shape=(2, 3), dtype=int32)


In [ ]:

#bai 4
ts4_random = tf.random.uniform(shape=[50], minval=5, maxval=10)

print(ts4_random)

tf.Tensor(
[9.573004  8.791376  9.923367  5.6374016 8.618528  8.562423  9.593727
 8.020974  5.365312  9.622734  9.082889  6.0961156 6.0904207 5.880726
 6.843548  9.000378  6.5119214 9.965195  8.864032  6.6484985 8.14128
 8.745199  7.8554907 5.4291463 9.544598  9.682928  5.399335  9.33033
 9.665761  5.0432625 9.73801   7.3623633 5.3983645 9.188219  9.398725
 6.7395897 5.71809   6.159507  8.659869  7.9728603 9.079193  5.8237977
 7.9008245 8.223892  5.644247  7.402547  7.0286746 5.2861543 6.509059
 8.914375 ], shape=(50,), dtype=float32)


In [ ]:
#bai5
ts5_range = tf.range(10,102,delta=2)
print(ts5_range)

tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


In [ ]:
#bai 5
ts_normal = tf.random.normal(shape=[3, 2], mean=0.0, stddev=2.0)
print(ts_normal)

tf.Tensor(
[[ 3.9801092   0.17654662]
 [-0.7135354   0.41010642]
 [ 4.0428653  -0.13001068]], shape=(3, 2), dtype=float32)


In [ ]:
#bai 6
ts_uniform = tf.random.uniform(shape=[3, 2], minval=0, maxval=2)
print(ts_uniform)

tf.Tensor(
[[0.7007706  0.6793952 ]
 [0.62441945 0.02823043]
 [1.4242504  1.1472833 ]], shape=(3, 2), dtype=float32)


In [ ]:
# bai 7
tensorX= tf.constant([[1,2],[2,3],[5,6]])
print(tensorX)
print(tf.random.shuffle(tensorX))

tf.Tensor(
[[1 2]
 [2 3]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [1 2]
 [5 6]], shape=(3, 2), dtype=int32)


In [ ]:
# bai 8

X = tf.random.uniform(shape=(10, 10, 3), minval=0, maxval=256, dtype=tf.int32)

shuffled_crop = tf.image.random_crop(X, size=[5, 5, 3])

print("Kích thước tensor gốc:", X.shape)
print("Kích thước sau khi random crop:", shuffled_crop.shape)
print("\nNội dung tensor sau khi cắt:\n", shuffled_crop.numpy())

Kích thước tensor gốc: (10, 10, 3)
Kích thước sau khi random crop: (5, 5, 3)

Nội dung tensor sau khi cắt:
 [[[200   3  78]
  [218  84 124]
  [ 80 153 249]
  [218  62  60]
  [204  38 155]]

 [[ 25 255 211]
  [207 164 254]
  [180 156 125]
  [ 47 147 120]
  [249   3  81]]

 [[ 95  93  44]
  [140 238 154]
  [ 92 172 118]
  [157  20 131]
  [241 232  70]]

 [[127 212 143]
  [172   1  49]
  [223 210 183]
  [157 166 236]
  [  5 226  74]]

 [[ 34  49  45]
  [ 23 231 215]
  [205 242 233]
  [195  69 214]
  [145  55 144]]]


In [ ]:
# bai 10
ts_x = tf.random.uniform((5,),minval=0,maxval=999,dtype=tf.int32)
ts_y = tf.random.uniform((5,),minval=0,maxval=999,dtype=tf.int32)
print("tensor x: ",ts_x.numpy())
print("tensor y: ",ts_y.numpy())
#
result = tf.where(ts_x<ts_y,ts_x+ts_y,ts_x-ts_y) # so sanh tung phan tu tsX vs tsY
print("ket qua: ",result.numpy())

tensor x:  [686 693 930 267 873]
tensor y:  [140 219 651 424 872]
ket qua:  [546 474 279 691   1]



1) tf.linalg.inv(matrix) --> tìm ma trận nghịch đảo
2) tf.linalg.det(matrix) --> tính định thức ma trận vuông
3)

In [ ]:
# bai 11 : (3,2) va (2,3) khong cong duoc --> transpose 1 trong 2
ts1 = tf.random.uniform((3,2),minval=5,maxval=11,dtype=tf.int32)
ts2 = tf.random.uniform((2,3),minval=15,maxval=21,dtype=tf.int32)
print("ts1:\n",ts1.numpy())
print("ts2:\n",ts2.numpy())
# dao chieu tensor : tf.transpose
ts2_transpose = tf.transpose(ts2)
print("ts2 transpose:\n",ts2_transpose.numpy())
# chuyen phan tu o duong cheo thanh 0 de x+y van giu dg cheo x
# 1. xem phan tu duong cheo : tf.eye(n_dong ,n_cot,dtypee : bool )
diag_mask = tf.eye(num_rows=3,num_columns=2,dtype=tf.bool)
print("mask duong cheo:\n",diag_mask.numpy())
# 2. gan phan tu 0
final_ts2 = tf.where(diag_mask,0,ts2_transpose)
print("ts2 chuan hoa :\n",final_ts2.numpy())
# cong 2 tensor
result = tf.add(ts1,final_ts2)
print("ket qua:\n",result.numpy())

ts1:
 [[ 9  5]
 [ 6 10]
 [ 7  7]]
ts2:
 [[18 19 16]
 [20 19 20]]
ts2 transpose:
 [[18 20]
 [19 19]
 [16 20]]
mask duong cheo:
 [[ True False]
 [False  True]
 [False False]]
ts2 chuan hoa :
 [[ 0 20]
 [19  0]
 [16 20]]
ket qua:
 [[ 9 25]
 [25 10]
 [23 27]]
